package com.celfons.crud.config;

import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportRuntimeHints;

/**
 * Configuration for GraalVM native compilation hints.
 * Spring AOT will automatically handle most cases, but this provides
 * additional hints if needed for specific reflection or resource access.
 */
@Configuration
@ImportRuntimeHints(GraalVMConfig.CrudRuntimeHints.class)
public class GraalVMConfig {

    /**
     * Runtime hints for GraalVM native compilation.
     * Spring Boot 3.x with AOT will automatically generate most hints,
     * but this can be used for additional customizations if needed.
     */
    static class CrudRuntimeHints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            // Most hints are automatically generated by Spring AOT
            // Add custom hints here if needed for specific use cases
            
            // Example: Register DTO classes for reflection if needed
            // hints.reflection().registerType(UserCreateDTO.class, MemberCategory.INVOKE_DECLARED_CONSTRUCTORS);
            // hints.reflection().registerType(UserUpdateDTO.class, MemberCategory.INVOKE_DECLARED_CONSTRUCTORS);
            // hints.reflection().registerType(UserResponseDTO.class, MemberCategory.INVOKE_DECLARED_CONSTRUCTORS);
        }
    }
}